### ISSUE TITLE
blew up sometime after computer went to sleep?

### ISSUE THREAD

**Issue by cppforlife** [dpb587/ssoca#3]
```
Wed Nov 22 20:11:31 2017 OpenSSL: error:02001002:system library:fopen:No such file or directory
Wed Nov 22 20:11:31 2017 OpenSSL: error:2006D080:BIO routines:BIO_new_file:no such file
Wed Nov 22 20:11:31 2017 OpenSSL: error:140AD002:SSL routines:SSL_CTX_use_certificate_file:system lib
Wed Nov 22 20:11:31 2017 MANAGEMENT: Client disconnected
Wed Nov 22 20:11:31 2017 Cannot load inline certificate file
Wed Nov 22 20:11:31 2017 Exiting due to fatal error
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
2017/11/22 20:11:31 accept tcp 127.0.0.1:9010: use of closed network connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x10ddc8a]

goroutine 66 [running]:
bufio.(*Reader).fill(0xc420027f08)
	/var/vcap/packages/ssoca-golang/src/bufio/bufio.go:97 +0xfa
bufio.(*Reader).ReadSlice(0xc4201e4f08, 0x100000000000a, 0x2, 0x2b, 0x185e8f0, 0x104e300, 0x17bd960)
	/var/vcap/packages/ssoca-golang/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadBytes(0xc4201e4f08, 0x100a, 0x141f960, 0xc420016301, 0xc4202bc000, 0x136150d, 0xc420027d38)
	/var/vcap/packages/ssoca-golang/src/bufio/bufio.go:416 +0x66
bufio.(*Reader).ReadString(0xc420027f08, 0x100a, 0x1000, 0xc4202bc000, 0x1000, 0x1000)
	/var/vcap/packages/ssoca-golang/src/bufio/bufio.go:456 +0x38
github.com/dpb587/ssoca/service/openvpn/client/management.(*Client).handleConnection(0xc420308000, 0x0, 0x0)
	/var/vcap/data/compile/ssoca/gopath/src/github.com/dpb587/ssoca/service/openvpn/client/management/client.go:82 +0x10b
created by github.com/dpb587/ssoca/service/openvpn/client/management.(*Client).listen
	/var/vcap/data/compile/ssoca/gopath/src/github.com/dpb587/ssoca/service/openvpn/client/management/client.go:74 +0x122
```

**Comment by dpb587** [comment]
Thanks for documenting this as an issue. I believe this was fixed via c233efe9385648706334587af2a753c7f4749b40 in [v0.7.0+](https://github.com/dpb587/ssoca/releases/tag/v0.7.0).
